# Generated by Django 5.2.2 on 2025-09-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('no_of_days', models.IntegerField()),
                ('no_of_periods', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('no_of_breaks', models.IntegerField()),
                ('break1_after_period', models.IntegerField(blank=True, null=True)),
                ('break2_after_period', models.IntegerField(blank=True, null=True)),
                ('break3_after_period', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break1_duration', models.IntegerField(blank=True, null=True)),
                ('break2_duration', models.IntegerField(blank=True, null=True)),
                ('break3_duration', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
            options={
                'unique_together': {('user', 'class_name')},
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period_number', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='base.timetable')),
            ],
            options={
                'ordering': ['timetable', 'day', 'period_number'],
                'unique_together': {('timetable', 'day', 'period_number')},
            },
        ),
    ]
