# Generated by Django 5.2.6 on 2025-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_timetable_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='break1_after_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break2_after_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break3_after_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TimetableSlot',
        ),
    ]
