# Generated by Django 5.2.6 on 2025-09-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_timetable_break1_after_period_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('user', 'class_name')},
        ),
    ]
