# Generated by Django 4.2.8 on 2025-09-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='break1_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break2_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='break3_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
