# Generated by Django 4.2.8 on 2025-09-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_timetable_break1_duration_timetable_break2_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('period_number', models.IntegerField()),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='base.timetable')),
            ],
            options={
                'ordering': ['timetable', 'day', 'period_number'],
                'unique_together': {('timetable', 'day', 'period_number')},
            },
        ),
    ]
